# Generated by Django 2.2.5 on 2019-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191023_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='http://cloudrangers.com/blog/wp-content/uploads/2017/08/blog_default.png', max_length=500),
        ),
    ]
